# Generated by Django 5.1.4 on 2024-12-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='radius',
        ),
    ]
