# Generated by Django 5.1.4 on 2025-01-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_course_students_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='radius',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='main_app.student'),
        ),
    ]
