# Generated by Django 5.1.4 on 2025-01-11 01:07

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_attendancesession_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='qr_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='expiry_time',
            field=models.DateTimeField(default=main_app.models.default_expiry_time),
        ),
    ]
