# Generated by Django 5.1.4 on 2025-01-11 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_attendancesession_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='for_teachers',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher'),
        ),
    ]
